exclude: >
  (?x)^(
      test\.tsx\.snap$
  )$
repos:
  - repo: local
    hooks:
      - id: eslint-prettier
        name: Lint and Style
        language: system
        entry: bash -c 'pushd app; yarn format && yarn lint'
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
        exclude: ^chart/.*/templates/
      - id: end-of-file-fixer
        exclude: current_version\.txt
      - id: trailing-whitespace
        exclude: .*/__snapshots__/.*
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
