version: "3.9"

services:
  # cif:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   environment:
  #     - PGUSER=cif_app
  #     - PGPASSWORD=""
  #   depends_on:
  #       - db
  #   ports:
  #       - 3004:3004
  #   command: ["yarn", "dev"]
  #   volumes:
  #     - ./app:/app
  db:
    build:
      context: .
      dockerfile: dev/db/Dockerfile
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cif
    volumes:
      - "./dev/db/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  run-migrations:
    image: sqitch/sqitch:latest
    volumes:
      - "./schema:/repo"
    command: ["deploy", "db:postgresql://postgres:postgres@db:5432/cif"]
    depends_on:
      db:
        condition: service_healthy
