# Barebones example of dockerized app/deployment
version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/forum_example
    depends_on:
      - db
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--append-plugins",
        "postgraphile-plugin-connection-filter",
      ]
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forum_example
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./nextjs-docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./nextjs-docker:/app
      - /nextjs-docker/node_modules
      - /nextjs-docker/.next
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
