apiVersion: v2
name: cas-cif
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: cas-postgres
    version: "0.8.0"
    repository: https://bcgov.github.io/cas-postgres/
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: download-dags
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: cert-issue
    condition: cert-issue.enabled
  - name: cas-airflow-dag-trigger
    version: 1.0.7
    repository: https://bcgov.github.io/cas-airflow
    alias: deploy-db
  - name: nginx-sidecar
    repository: https://bcgov.github.io/cas-template-app
    version: 0.1.8
