app:
  showKCLogin: true
  sitewide_notice:
    content: <div class="alert alert-warning">This is the DEV environment.</div>

nginx-sidecar:
  hostName: dev.cif.gov.bc.ca

db:
  preUpgradeCommand: |
    psql -v "ON_ERROR_STOP=1" <<EOF
      drop schema sqitch if exists cascade;
      drop schema cif if exists cascade;
      drop schema cif_private if exists cascade;
    EOF

cert-issue:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca

deploy-db:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca

download-dags:
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
