app:
  sitewide_notice:
    content: <div class="alert alert-warning">This is the TEST environment.</div>

nginx-sidecar:
  hostName: cas-cif-test.apps.silver.devops.gov.bc.ca

db:
  preUpgradeCommand: |
    psql<<EOF
      select pg_terminate_backend(pid) from pg_stat_activity where
      -- don't kill my own connection!
      pid <> pg_backend_pid()
      -- don't kill the connections to other databases
      and datname = '$(CIF_DATABASE)';
      drop database if exists $(CIF_DATABASE);
      drop user if exists $(CIF_USER);
    EOF

cert-issue:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

deploy-db:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

download-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca
