defaultImageTag: latest # set to the GIT SHA1 in the Makefile
defaultImagePullPolicy: IfNotPresent
artifactoryServiceAccount: cas-artifact-download # The name of the ArtifactoryServiceAccount object created in the cas-provision chart

replicaCount: 2

image:
  app:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-cif-app
  schema:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-cif-schema
  psql:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-postgres
    tag: "0.3.0"
  casShelf:
    repository: artifacts.developer.gov.bc.ca/google-docker-remote/ggl-cas-storage/cas-shelf-tfe-add-app
    tag: "0.1"

app:
  sitewide_notice:
    content: ""
  port: 3000
  probesPort: 9000
  showKCLogin: false

db:
  name: cif
  appUser: cifapp
  ownerUser: cif
  # A shell script that will be executed in a pre-upgrade job, on the psql image.
  preUpgradeCommand: ~

nginx-sidecar:
  hostName: ~
  # set to false to deploy the application with an insecure route,
  # and issue an SSL certificate using acme.sh
  sslTermination: true
  objectNamePrefix: cas-cif
  port: 3001
  internalPort: 3000
  caServerSecret: ~ # pragma: allowlist secret
  caServerKey: ~
  caAccountEmail: ggircs@gov.bc.ca
  storageClassName: netapp-file-standard
  renewalDays: 60

resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

cert-issue:
  enabled: false
  airflowEndpoint: ~
  dagId: cas_cif_acme_issue
  helm:
    hook: post-install

deploy-db:
  airflowEndpoint: ~
  dagId: cas_cif_deploy_db
  helm:
    hook: false

download-dags:
  airflowEndpoint: ~
  dagId: fetch_and_save_dag_from_github
  helm:
    hook: "pre-install,pre-upgrade"

ggircs:
  service: cas-ggircs-patroni
  instanceName: cas-ggircs

metabase:
  instanceName: cas-metabase
