version: "3.3"
services:
  api:
    build:
      context: .
    command: /app/start.sh
    volumes:
      - type: bind
        source: ./
        target: /app
        consistency: cached
    env_file:
      - .env
    environment:
      PORT: 8000
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_HOST_URL: "${MINIO_HOST_URL}"
      STORAGE_API_KEY: "${STORAGE_API_KEY}"
    ports:
      - "8000:8000"
  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    volumes:
      - minio-volume:/data:z
      - type: bind
        source: ./scripts/minio-dev.sh
        target: /mnt/minio-dev.sh
        consistency: cached
    ports:
      - "9000:9000"
    env_file:
      - local.env
    entrypoint: /mnt/minio-dev.sh
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-volume:
