{{- if .Values.db.preUpgradeCommand }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-cif.fullname" . }}-db-pre-upgrade
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels: {{ include "cas-cif.labels" . | nindent 8 }}
      name: {{ template "cas-cif.fullname" . }}-db-pre-upgrade
    spec:
      restartPolicy: Never
      imagePullSecrets: {{ include "cas-cif.imagePullSecrets" . | nindent 8 }}
      containers:
        - env:
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password-superuser
                  name: {{ template "cas-cif.fullname" . }}-patroni
            - name: PGPORT
              value: "5432"
            - name: PGHOST
              value: {{ template "cas-cif.fullname" . }}-patroni
            - name: CIF_USER
              valueFrom:
                secretKeyRef:
                  key: database-owner-user
                  name: {{ template "cas-cif.fullname" . }}
            - name: CIF_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-owner-password
                  name: {{ template "cas-cif.fullname" . }}
            - name: CIF_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ template "cas-cif.fullname" . }}
          name: {{ template "cas-cif.fullname" . }}-db-pre-upgrade
          image: {{ .Values.image.psql.repository }}:{{ default .Values.defaultImageTag .Values.image.psql.tag }}
          imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.psql.pullPolicy }}
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command:
            - /usr/bin/env
            - bash
            - -c
            - |
              set -euo pipefail;
{{ .Values.db.preUpgradeCommand | indent 14 }}
{{- end}}
