{{- $secretName := (printf "%s-%s-%s" "gcp" .Release.Namespace "cif-backups-service-account-key") }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- $gcsKey := "test-key" }}
{{- if $secret.data }}
{{- $gcsKey = index $secret.data "credentials.json" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cas-cif.fullname" . }}-pgbackrest
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
type: Opaque
stringData:
  gcs.conf: |-
    [global]
      repo1-gcs-key=/etc/pgbackrest/conf.d/gcs-key.json
  gcs-key.json: {{ $gcsKey | b64dec | quote }}
