apiVersion: v1
kind: Service
metadata:
  name: {{ template "cas-cif.fullname" . }}
  labels: {{ include "cas-cif.labels" . | nindent 4 }}

spec:
  ports:
  - name: {{ template "cas-cif.fullname" . }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: 3000
  selector: {{ include "cas-cif.selectorLabels" . | nindent 4 }}
    component: app
  sessionAffinity: None
  type: ClusterIP
