name: Test sqitch changes immutability

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  check_immutable_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.bin/sqitch-check-immutable-files.sh schema main
