name: Test CIF App

on:
  push:
    branches-ignore:
      - main

jobs:
  install-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache-dev-dependencies
        with:
          path: |
            ~/.asdf
            ~/.perl5
            ~/.cache/yarn
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.tool-versions', 'cpanfile', 'app/yarn.lock') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v1
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      - name: install pg perl library
        run: sudo apt-get install -y libpq-dev libdbd-pg-perl
      - run: make install_dev_tools
      - run: yarn install --frozen-lockfile
        working-directory: ./app
